# Generated by Django 4.2.9 on 2026-02-05 18:02

from django.db import migrations, models
import django.db.models.deletion
import tests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('teacher', "O'qituvchi"), ('student', 'Talaba')], default='teacher', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('Matematika', 'Matematika'), ('Tarix', 'Tarix'), ('Ona tili', 'Ona tili'), ('Ingliz tili', 'Ingliz tili'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Fizika', 'Fizika'), ('Geografiya', 'Geografiya')], max_length=50)),
                ('access_code', models.CharField(db_index=True, default=tests.models.generate_access_code, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to='tests.user')),
            ],
            options={
                'db_table': 'tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('cash', 'Naqd')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Bekor qilindi')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tests.user')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_telegram_id', models.BigIntegerField()),
                ('student_name', models.CharField(max_length=255)),
                ('answers', models.JSONField()),
                ('score', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+ (90-100%)'), ('A', 'A (80-89%)'), ('B', 'B (70-79%)'), ('C', 'C (60-69%)'), ('D', 'D (50-59%)'), ('F', 'F (0-49%)')], max_length=2, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tests.test')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('test', 'student_telegram_id')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_type', models.CharField(choices=[('choice', 'Variantli'), ('writing', 'Yozma')], default='choice', max_length=10)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['question_number'],
                'unique_together': {('test', 'question_number')},
            },
        ),
    ]
