# Generated by Django 4.2.9 on 2026-02-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('info', "Ma'lumot"), ('warning', 'Ogohlantirish'), ('danger', 'Xavf')], default='info', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='creator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
