# Generated by Django 4.2.9 on 2026-02-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_announcement_test_creator_name_test_expires_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='test',
            name='submission_mode',
            field=models.CharField(choices=[('single', 'Faqat 1 marta'), ('multiple', "Ko'p marta (Cheksiz)")], default='single', max_length=10),
        ),
    ]
