# Generated by Django 4.2.9 on 2026-02-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
