# Generated by Django 4.2.9 on 2026-02-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_points_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('tur1', '1-tur (1-40)'), ('tur2', '2-tur (41-43 manual)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Tarix', 'Tarix'), ('Ona tili', 'Ona tili'), ('Ingliz tili', 'Ingliz tili'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Fizika', 'Fizika'), ('Geografiya', 'Geografiya'), ('Rus tili', 'Rus tili'), ('Qoraqalpoq tili', 'Qoraqalpoq tili')], max_length=50),
        ),
    ]
