# Generated by Django 4.2.9 on 2026-02-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_sub_type_alter_test_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Variantli'), ('writing', 'Yozma'), ('manual', "Qo'lda baholanadi")], default='choice', max_length=10),
        ),
    ]
