# Generated by Django 4.2.9 on 2026-02-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_logit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='ability_logit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='scaled_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='test',
            name='is_calibrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(choices=[('Matematika', 'Matematika'), ('Tarix', 'Tarix'), ('Ona tili va adabiyot', 'Ona tili va adabiyot'), ('Ingliz tili', 'Ingliz tili'), ('Kimyo', 'Kimyo'), ('Biologiya', 'Biologiya'), ('Fizika', 'Fizika'), ('Geografiya', 'Geografiya'), ('Rus tili', 'Rus tili'), ('Qoraqalpoq tili', 'Qoraqalpoq tili')], max_length=50),
        ),
    ]
