# Generated by Django 4.2.9 on 2026-02-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_question_difficulty_logit_submission_ability_logit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (>70%)'), ('A', 'A (65-69.9%)'), ('B+', 'B+ (60-64.9%)'), ('B', 'B (55-59.9%)'), ('C+', 'C+ (50-54.9%)'), ('C', 'C (46-49.9%)'), ('F', 'F (0-45.9%)')], max_length=2, null=True),
        ),
    ]
