# Generated by Django 4.2.9 on 2026-02-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('teacher', "O'qituvchi"), ('student', 'Talaba'), ('user', 'Foydalanuvchi')], default='user', max_length=15),
        ),
    ]
