# Generated by Django 4.2.9 on 2026-02-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('target_roles', models.JSONField(default=list)),
                ('total_users', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Yuborilmoqda'), ('completed', 'Tugallandi'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='tests.user')),
            ],
            options={
                'db_table': 'broadcast_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
