# Generated by Django 4.2.9 on 2026-02-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_broadcasthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcasthistory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='broadcasts/files/'),
        ),
        migrations.AddField(
            model_name='broadcasthistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='broadcasts/images/'),
        ),
    ]
