# Generated by Django 4.2.9 on 2026-02-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_broadcasthistory_file_broadcasthistory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
