# Generated by Django 4.2.9 on 2026-02-11 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_test_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='completed_at',
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='tests.broadcasthistory')),
            ],
            options={
                'db_table': 'broadcast_recipients',
                'indexes': [models.Index(fields=['broadcast', 'telegram_id'], name='broadcast_r_broadca_b0c715_idx')],
            },
        ),
    ]
