# Generated by Django 4.2.9 on 2026-02-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_systemsettings_paymentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_tests_used',
            field=models.IntegerField(default=0),
        ),
    ]
