# Generated by Django 4.2.9 on 2026-02-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_user_free_tests_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='free_test_limit',
            field=models.IntegerField(default=5),
        ),
    ]
