# Generated by Django 4.2.9 on 2026-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_systemsettings_free_test_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='price_per_test',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
