# Generated by Django 4.2.9 on 2026-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='bot_link',
            field=models.URLField(default='https://t.me/Kamunal_manitoring_bot', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='channel_link',
            field=models.URLField(default='https://t.me/Titul_testlar', max_length=255),
        ),
    ]
