# Generated by Django 4.2.9 on 2026-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_systemsettings_bot_link_systemsettings_channel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='mandatory_channels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
