# Generated by Django 4.2.9 on 2026-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_systemsettings_mandatory_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='support_link',
            field=models.URLField(default='https://t.me/Bobomurod2004', max_length=255),
        ),
    ]
